name: Build and Test Android Emulator

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t android-emulator:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 5554:5554 -p 5555:5555 -p 5900:5900 -p 6080:6080 --name android-emulator android-emulator:latest

      - name: Set up SSH tunnel with Serveo
        run: |
          ssh -o StrictHostKeyChecking=no -i serveo_key -R 80:localhost:6080 serveo.net 

      - name: Test the Android emulator container
        run: |
          docker ps
          sleep 30 # Give some time for the emulator to start
          curl --fail http://localhost:6080 || (docker logs android-emulator && exit 1)
